### PR TITLE
chore: remove workflow cache actions.

### PR DESCRIPTION
**Pull request by kyliehe616**
### What this PR does
Address #58 by removing the cache related blocks. Workflows won't check for cached files.

~~TODO: remove cached files.~~

### How it was tested
Tested on a forked repo. No cache files were created with the modified workflow. 

### PR checklist

- [x] No API keys or other secrets committed to source?
- [x] New functionality is added alongside appropriate tests?
- [x] All source files have the following header?

```
# Copyright (c) {YEAR} Cohere Inc. and its affiliates.
#
# Licensed under the MIT License (the "License");
# you may not use this file except in compliance with the License.
#
# You may obtain a copy of the License in the LICENSE file at the top
# level of this repository.
```

### CODE REVIEW

**Comment by yichern** [comment]
When committing to a working branch, will the removal of the cached venvs lead to slower feedback on whether the commit passes tests?

**Comment by eddotman** [comment]
Yeah I think the case of the slow builds on working branches is relatively rare to be blocking -- e.g., you should be able to pytest locally unless we are specifically debugging the CI workflow itself.

**Review by eddotman — APPROVED** [review]
LGTM! Thanks for testing this on a fork 🚀

**Comment by kyliehe616** [comment]
Sure! I'm thinking about using the `chore` tag for this PR. 
--I used [this](https://gist.github.com/joshbuchea/6f47e86d2510bce28f8e7f42ae84c716) for reference.

Also, should we add semantic prefix options to the CONTRIBUTORS.md file?

**Comment by kyliehe616** [comment]
Each workflow takes 1.5 min to run w/o caching vs <0.5 min to run w/ caching.

**Pull request merged**
