### PR TITLE
[CNV-263] feat: add typewriter effect for latest model response

### PR DESCRIPTION
**Pull request by yichern**
- #98 👈

CNV-263
### What this PR does
- Adds an animation for the latest model response in the Streamlit demo
- PR on streamlit-talk: https://github.com/yichern/st-chat/pull/1

### How it was tested

https://user-images.githubusercontent.com/32623504/216418736-b32fb767-8092-49b3-9257-670635b625e9.mov

### PR checklist

- [x] No API keys or other secrets committed to source?
- [ ] New functionality is added alongside appropriate tests?
- [x] All source files have the following header?

```
# Copyright (c) {YEAR} Cohere Inc. and its affiliates.
#
# Licensed under the MIT License (the "License");
# you may not use this file except in compliance with the License.
#
# You may obtain a copy of the License in the LICENSE file at the top
# level of this repository.
```

### CODE REVIEW

**Comment by irombie** [comment]
Awesome work!! LGTM

**Comment by yichern** [comment]
Ah I see, I think that might require the chat custom component to send a value to Streamlit to indicate that it is still typewriting, then send another value to indicate typewriting is complete. I’m not fully confident Streamlit supports this, but if you think it’ll be important to disable the message input during typewriting I can give that a shot

**Comment by irombie** [comment]
Assuming that the users will behave nicely, I do not think that it will be a problem. However, it results in some wonky behavior if they do not. I am not sure if it is a must-fix or not, but I have added one case where it results in some weird behavior:
https://www.loom.com/share/b4f092de71c0457892da5098fb4e599f

Let me know what you think!

**Comment by yichern** [comment]
Closing this as https://github.com/cohere-ai/sandbox-conversant-lib/pull/99 makes this obsolete

**Pull request closed without merging**
